spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sf_food_trucks_db
    username: foodtruck
    password: foodtruck
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true